
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use the version of Node.js you need
      - name: run adding core  
        run: | 
          npm init -y
          npm install @actions/core

      - name: Run My Custom Action
        id: my-action
        uses: ./my-custom-action
        with:
          message: 'Hello, custom action!'
