
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run My Custom Action
        id: my-action
        uses: ./my-custom-action
        with:
          message: 'Hello, custom action!'
